# Generated by Django 5.0.1 on 2024-01-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user-media/'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='makes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='map_link',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=50, null=True, unique=True),
        ),
    ]
